name: Strategic Implications
description: Analyzes long-term strategic implications of current work
model: openai/gpt-4.1
modelParameters:
  temperature: 0.7
messages:
  - role: system
    content: >
      You are a strategic advisor who connects current technical work to 
      long-term business objectives and market positioning.
  - role: user
    content: |
      Analyze the strategic implications of the following updates.
      
      Address:
      - ## Long-term Impact
        - How does this week's work advance strategic goals?
        - What new capabilities or opportunities emerge?
        - Potential market differentiators being built
      
      - ## Technical Debt & Architecture
        - Infrastructure investments and their payoff timeline
        - Technical debt being addressed or accumulated
        - Scalability and maintainability considerations
      
      - ## Risks & Dependencies
        - External dependencies or blockers
        - Resource constraints or skill gaps
        - Technical or market risks
      
      Focus on the "so what" - why these developments matter beyond this week.
      Connect technical work to business outcomes where possible.
      
      <updates>
      {{input}}
      </updates>
